#!/usr/bin/env python3
"""Build the repository's machine-readable dataset manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "dataset_manifest__JSON.json"

DATASET_CATALOG = {
    "edisi-IV": {
        "source_urls": ["https://github.com/bachors/KBBI.sql"],
        "license_status": "Badan Bahasa ownership; no open license recorded",
        "provenance_status": "source snapshot is not revision-pinned",
        "notes": "KBBI Edisi IV source data; preserve ownership notice.",
    },
    "baku-nonbaku": {
        "source_urls": ["https://github.com/ManaSiWibi/KBBI-SQL-database"],
        "license_status": "project-generated; no independent data license recorded",
        "provenance_status": "generated provenance incomplete",
        "notes": "Generated by GPT-5.6 Sol; prompt, date, and human review record are unavailable.",
    },
    "sinonim": {
        "source_urls": ["https://github.com/ManaSiWibi/KBBI-SQL-database"],
        "license_status": "project-generated; no independent data license recorded",
        "provenance_status": "generated provenance incomplete",
        "notes": "Generated by GPT-5.6 Sol; prompt, date, and human review record are unavailable.",
    },
    "antonim": {
        "source_urls": ["https://github.com/ManaSiWibi/KBBI-SQL-database"],
        "license_status": "project-generated; no independent data license recorded",
        "provenance_status": "generated provenance incomplete",
        "notes": "Generated by GPT-5.6 Sol; prompt, date, and human review record are unavailable.",
    },
    "kamus-alay": {
        "source_urls": [
            "https://github.com/nasalsabila/kamus-alay",
            "https://huggingface.co/datasets/SEACrowd/kamus_alay",
        ],
        "license_status": "source license not identified in the imported snapshot",
        "provenance_status": "source cited; redistribution terms require confirmation",
        "notes": "Source comments were intentionally omitted from the canonical copy.",
    },
    "indolex": {
        "source_urls": [
            "https://www.kaggle.com/datasets/binhashem/indolex-indonesian-academic-lexical-dataset",
        ],
        "license_status": "CC BY-NC-SA 4.0 according to the source dataset",
        "provenance_status": "source and imported tables documented",
        "notes": "Definition text was not copied; frequency and root enrichment are included.",
    },
    "kbbi-v6": {
        "source_urls": ["https://github.com/Definisi/kbbi"],
        "license_status": "Badan Bahasa ownership; no open data license recorded",
        "provenance_status": "source revision pinned",
        "notes": "Extracted KBBI Edisi VI application snapshot.",
    },
    "kbbi-v5": {
        "source_urls": [
            "https://huggingface.co/datasets/Lyon28/kamus-besar-bahasa-indonesia",
        ],
        "license_status": "source metadata conflicts with Badan Bahasa ownership notice",
        "provenance_status": "source revision and input hash pinned",
        "notes": "Exact duplicate rows were removed; raw etimologi text is preserved alongside parsed data.",
    },
    "kaikki": {
        "source_urls": [
            "https://kaikki.org/idwiktionary/Bahasa%20Indonesia/index.html",
            "https://kaikki.org/idwiktionary/Bahasa%20Indonesia%20Peranakan/index.html",
        ],
        "license_status": "Wiktionary CC BY-SA/GFDL terms apply",
        "provenance_status": "source files and hashes documented",
        "notes": "Wiktextract JSONL was normalized into JSON envelopes.",
    },
    "tesaurus-pusat-bahasa": {
        "source_urls": ["https://github.com/victoriasovereigne/tesaurus"],
        "license_status": "Badan Bahasa ownership; imported source license unclear",
        "provenance_status": "source cited; snapshot provenance documented",
        "notes": "Synonym and antonym relations remain nested under each entry.",
    },
    "antonim-tesaurus": {
        "source_urls": [
            "https://github.com/riochr17/Daftar-Antonim-Tesaurus-Bahasa-Indonesia",
        ],
        "license_status": "source license not identified in the imported snapshot",
        "provenance_status": "source and transformation documented",
        "notes": "Directed antonym pairs are preserved as supplied by the source.",
    },
    "wordnet-bahasa": {
        "source_urls": ["https://wn-msa.sourceforge.net/eng/index.html"],
        "license_status": "MIT according to the source repository",
        "provenance_status": "release and input hashes pinned",
        "notes": "The enrichment file joins every Indonesian membership row to zero or more definitions.",
    },
    "malindo-morph": {
        "source_urls": ["https://github.com/matbahasa/MALINDO_Morph"],
        "license_status": "CC BY 4.0 according to the source README",
        "provenance_status": "source revision and input hash pinned",
        "notes": "Duplicate source IDs are retained because they represent source rows.",
    },
    "leipzig": {
        "source_urls": [
            "https://corpora.uni-leipzig.de/en?corpusId=ind_mixed_2013",
            "https://downloads.wortschatz-leipzig.de/corpora/ind_mixed_2013_100K.tar.gz",
            "https://wortschatz.informatik.uni-leipzig.de/documents/Format_Download_File-eng.pdf",
        ],
        "license_status": "CC BY stated by Leipzig documentation; source terms still apply",
        "provenance_status": "archive hash and normalized subset documented",
        "notes": "The similarity feature is a reproducible local derivation, not a copied portal result.",
    },
    "leipzig-wikipedia-2021": {
        "source_urls": [
            "https://dict.wortschatz-leipzig.de/en?corpusId=ind_wikipedia_2021",
            "https://downloads.wortschatz-leipzig.de/corpora/ind_wikipedia_2021_100K.tar.gz",
            "https://wortschatz.informatik.uni-leipzig.de/documents/Format_Download_File-eng.pdf",
        ],
        "license_status": "CC BY stated by Leipzig documentation; source terms still apply",
        "provenance_status": "archive hash and normalized subset documented",
        "notes": "2021 Wikipedia-only corpus; kept separate from the mixed 2013 corpus because genre changes the distribution.",
    },
    "leipzig-wikipedia-2026": {
        "source_urls": [
            "https://dumps.wikimedia.org/idwiki/20260901/",
            "https://dumps.wikimedia.org/idwiki/20260901/idwiki-20260901-pages-articles.xml.bz2",
            "https://dumps.wikimedia.org/idwiki/20260901/idwiki-20260901-pages-articles1.xml-p1p1500000.bz2",
            "https://meta.wikimedia.org/wiki/Terms_of_use/en",
        ],
        "license_status": "Wikimedia/Wikipedia CC BY-SA/GFDL and third-party terms apply",
        "provenance_status": "dump revision, part, prefix hash, and deterministic transformation documented",
        "notes": "100K-sentence derived prefix sample; Leipzig-compatible schema, not an official Leipzig corpus; rare relations are frequency-filtered.",
    },
    "etymology-db": {
        "source_urls": [
            "https://github.com/droher/etymology-db",
            "https://github.com/droher/etymology-db/releases/tag/2023-12",
            "https://github.com/droher/etymology-db/releases/download/2023-12/etymology.csv.gz",
            "https://github.com/droher/etymology-db/blob/master/README.md",
        ],
        "license_status": "CC ShareAlike 3.0 according to the source README; underlying Wiktionary terms apply",
        "provenance_status": "release tag, source commit, asset hash, and Indonesian-language row filter documented",
        "notes": "Indonesian-only slice; group_* rows preserve nested source structure; source parser reports no systematic validation.",
    },
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_envelope(path: Path) -> tuple[str, object]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or len(value) != 1:
        raise ValueError(f"{path}: expected one-key JSON envelope")
    return next(iter(value)), next(iter(value.values()))


def file_record(path: Path) -> dict[str, object]:
    root_key, value = read_envelope(path)
    return {
        "path": path.relative_to(ROOT).as_posix(),
        "root_key": root_key,
        "value_type": "array" if isinstance(value, list) else type(value).__name__,
        "record_count": len(value) if isinstance(value, list) else None,
        "sha256": sha256(path),
    }


def build(generated_at: str) -> dict[str, object]:
    files = sorted(
        path
        for path in ROOT.rglob("*__JSON.json")
        if path != MANIFEST_PATH
    )
    by_directory: dict[str, list[dict[str, object]]] = {}
    for path in files:
        directory = path.relative_to(ROOT).parts[0]
        by_directory.setdefault(directory, []).append(file_record(path))

    unknown = sorted(set(by_directory) - set(DATASET_CATALOG))
    missing = sorted(set(DATASET_CATALOG) - set(by_directory))
    if unknown or missing:
        raise ValueError(f"catalog mismatch; unknown={unknown}, missing={missing}")

    datasets = []
    for directory in sorted(DATASET_CATALOG):
        metadata = DATASET_CATALOG[directory]
        datasets.append(
            {
                "directory": directory,
                "files": by_directory[directory],
                **metadata,
            }
        )
    return {
        "dataset_manifest": {
            "schema_version": 1,
            "canonical_format": "JSON",
            "generated_at": generated_at,
            "datasets": datasets,
        }
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--generated-at",
        default=datetime.now(timezone.utc).date().isoformat(),
        help="UTC date stored in the manifest (default: today)",
    )
    args = parser.parse_args()
    MANIFEST_PATH.write_text(
        json.dumps(build(args.generated_at), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {MANIFEST_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
